port: 9002
upstream: 127.0.0.1:9009
# Path to hit to get debug from each of the handlers.
debug_path: /_debug
health_path: /logo

# Change the handler to suit your type of site. See handler.py.
handlers:
  - wurfl: devproxy.handlers.wurfl_handler.scientia_mobile_cloud_resolution.ScientiaMobileCloudResolutionTouchHandler

wurfl:
  # All keys in Memcached are prefixed with this
  cache_prefix: devproxy
  cache_lifetime: 86400 # defaults to 0, which means it won't expire unless
                        # memcached decides to delete the key based on its
                        # least-recently-used counters when memory fills up.
  smcloud_api_key: YOUR_WURFL_CLOUD_API_KEY
  # Connect to Memcached with the following parameters
  memcached:
    host: localhost
    port: 11211
