sudo: false
language: python
cache:
  pip: true
  yarn: true
  directories:
    - node_modules

services:
  - redis-server
  
env:
  - TOXENV=django111

before_install:
  - nvm install
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH


install:
  - pip install tox

script: tox