sudo: false
language: python
cache: pip

cache:
  yarn: true
  directories:
    - node_modules

env:
  - TOXENV=django19

install:
  - nvm install
  - npm install
  - npm run build
  - pip install tox

script: tox
